config/routes.rb
Rails.application.routes.draw do

  root to: 'players#index', as: 'root'

  get '/players/levelup/:id', to: 'players#levelup', as: 'player_levelup'
  post '/player/autocomplete', to: 'players#autocomplete', as: 'player_autocomplete'
  resources :races
  resources :roles
  resources :players

end

app/models/player.rb
class Player 
	include Mongoid::Document
	field :name
	field :level
	belongs_to :role
	belongs_to :race
end

app/models/race.rb
class Race 
	include Mongoid::Document
	field :name
	has_many :players
end

app/models/role.rb
class Role 
	include Mongoid::Document
	field :name
	field :category
	has_many :players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

   def index
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)



    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def levelup
      @player = Player.find(params[:id])

      @player.level = String(Integer(@player.level) + 1)
      respond_to do |format|
        if(@player.save)
            format.html { redirect_to @player, notice: 'Player gained a level.' }
            format.json { render :show, status: :ok, location: @player }

        else
          format.html { redirect_to @player, notice: 'Player didn\'t get a level.'  }
          format.json { render json: @player.errors, status: :unprocessable_entity }
        end
      end
  end

  def autocomplete
      name = params[:name_startsWith]
      @players = Player.any_of(name: /#{name}/)
      respond_to do |format|

        if( @players)
            format.json { render json: @players, status: :ok, location: @player }
        else
            format.html { redirect_to @player, notice: 'User was successfully created.' }
            format.js   {}
            format.json { render json: @player, status: :created, location: @player }
        end
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :role, :level, :race)
    end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]

  # GET /races
  # GET /races.json
  def index
    @races = Race.all
  end

  # GET /races/1
  # GET /races/1.json
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: 'Race was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params.require(:race).permit(:name)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobGlasses</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.collection_select(:role, Role.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :race %><br>
    <%= f.collection_select(:race, Race.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
$(document).ready(function() {

  $("#new_player").validate({
    rules: {
      "player[name]": {required: true},
      "player[role]": {required: true},
      "player[race]": {required: true },
      "player[level]": {required: true}

    }
  });

});
</script>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th>Race</th>
      <th>Level</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.role.name %></td>
        <td><%= player.race.name %></td>
        <td><%= player.level %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouveau Joueur', new_player_path %>
<%= link_to 'Voir les Roles', roles_path %>
<%= link_to 'Voir les Races', races_path %>
<div style="margin-top: 50px">
  <input id="player_selected"   name="playername" type="text" placeholder="Chercher joueur ..."/>
  <
</div>


<script>

$(document).ready(function() {
  $('#player_selected').autocomplete({
    source: function(requete,response){
        $.ajax({

            url : "<%= player_autocomplete_path %>", // on appelle le script JSON
            dataType : 'json', // on spécifie bien que le type de données est en JSON
              data : {
                          
                name_startsWith : $('#player_selected').val(), // on donne la chaîne de caractère tapée dans le champ de recherche

                maxRows : 15

            },
            type: 'POST',
            success : function(donnee){ // on se prépare à renvoyer les données réceptionnées grâce à l'évènement de succès
                  response($.map(donnee, function(objet){

                    return objet.name; // on retourne cette forme de suggestion

                }));
            }
        });
    }
  });
});
</script>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @player.role.name %>
</p>

<p>
  <strong>Race:</strong>
  <%= @player.race.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @player.level %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>
<%= link_to 'levelUp', player_levelup_path(@player) %> |

app/views/races/_form.html.erb
<%= form_for(@race) do |f| %>
  <% if @race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% @race.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script>
$(document).ready(function() {

  $("#new_race").validate({
    rules: {
      "race[name]": {required: true},
    }
  });

});
</script>

app/views/races/edit.html.erb
<h1>Editing Race</h1>

<%= render 'form' %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

app/views/races/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Races</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.name %></td>
        <td><%= link_to 'Show', race %></td>
        <td><%= link_to 'Edit', edit_race_path(race) %></td>
        <td><%= link_to 'Destroy', race, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race', new_race_path %>
<%= link_to 'Retour vue joueur', root_path %>

app/views/races/new.html.erb
<h1>New Race</h1>

<%= render 'form' %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @race.name %>
</p>

<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script>
$(document).ready(function() {

  $("#new_role").validate({
    rules: {
      "role[name]": {required: true},
      "role[category]": {required: true},
    }
  });

});
</script>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= role.category %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>
<%= link_to 'Retour vue joueur', root_path  %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form' %>



<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @role.category %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>